# Nama workflow yang akan muncul di tab "Actions" GitHub
name: Deploy to VPS via Docker Hub

# Pemicu: Workflow ini akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Menggunakan environment terbaru yang disediakan GitHub
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repository Anda
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Login ke Docker Hub
      # Menggunakan kredensial yang sudah Anda simpan di GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3: Menyiapkan Docker Buildx untuk proses build yang efisien
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Langkah 4: Build dan Push image Docker untuk Backend
      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./stmadb-portal-be
          file: ./stmadb-portal-be/Dockerfile
          push: true
          no-cache: true
          # Tag image dengan format Docker Hub: username/nama-image:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stmadb-portal-be:latest

      # Langkah 5: Build dan Push image Docker untuk Frontend
      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./stmadb-portal-fe
          file: ./stmadb-portal-fe/Dockerfile
          push: true
          # Menyuntikkan URL API publik ke dalam proses build Next.js
          build-args: |
            NEXT_PUBLIC_API_URL=http://apps.smkn1adw.sch.id/api/v1
          # Tag image dengan format Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stmadb-portal-fe:latest

      # Langkah 6: Deploy ke VPS melalui SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Pindah ke direktori project di VPS
            cd /home/apps/stmadb-portal

            # Tarik (pull) versi terbaru dari kedua image Docker dari Docker Hub
            docker compose pull

            # Matikan dan nyalakan kembali semua service dengan image baru
            docker compose up -d

            # Hapus image lama yang tidak terpakai untuk menghemat ruang disk
            docker image prune -f